### ISSUE TITLE
Getting duplicate libraries in _PodsDummy_Pods_APBToygerFacade

### ISSUE THREAD

**Issue by jpmsmart** [zoloz-pte-ltd/zoloz-demo-ios#5]
```bash


ld: warning: ignoring duplicate libraries: '-lc++'
duplicate symbol '_OBJC_CLASS_$_PodsDummy_Pods_APBToygerFacade' in:
    /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][32](Pods-APBToygerFacade-dummy.o)
    /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][31](Pods-APBToygerFacade-dummy.o)
duplicate symbol '_OBJC_METACLASS_$_PodsDummy_Pods_APBToygerFacade' in:
    /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][32](Pods-APBToygerFacade-dummy.o)
    /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][31](Pods-APBToygerFacade-dummy.o)
ld: 2 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by hecklerhack** [comment]
> ld: warning: ignoring duplicate libraries: '-lc++'
> duplicate symbol '_OBJC_CLASS_$_PodsDummy_Pods_APBToygerFacade' in:
>     /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][32](Pods-APBToygerFacade-dummy.o)
>     /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][31](Pods-APBToygerFacade-dummy.o)
> duplicate symbol '_OBJC_METACLASS_$_PodsDummy_Pods_APBToygerFacade' in:
>     /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][32](Pods-APBToygerFacade-dummy.o)
>     /Users/jpm/workspace/kiq/fe-kiq/ios/Pods/zolozkit/APBToygerFacade.framework/APBToygerFacade[arm64][31](Pods-APBToygerFacade-dummy.o)
> ld: 2 duplicate symbols
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

This also happens to our iOS application when we upgraded React Native 0.67 to 0.75.

**Comment by jpmsmart** [comment]
I was able to fix this issue by editing `project.pbxproj` this file.

Find OTHER_LDFLAGS, and put these in the same sequence.

```
OTHER_LDFLAGS = (
					"$(inherited)",
					"-ObjC",
					"-lc++",
					"-ld64",
					"-Wl,-no_fixup_chains",
				);
```

```

LD_RUNPATH_SEARCH_PATHS = (
					"$(inherited)",
					"@executable_path/Frameworks",
					"@loader_path/Frameworks",
				);

```

It took me 2 days to figure this out. I hope it helps

**Comment by hecklerhack** [comment]
> I was able to fix this issue by editing `project.pbxproj` this file.
> 
> Find OTHER_LDFLAGS, and put these in the same sequence.
> 
> ```
> OTHER_LDFLAGS = (
> 					"$(inherited)",
> 					"-ObjC",
> 					"-lc++",
> 					"-ld64",
> 					"-Wl,-no_fixup_chains",
> 				);
> ```
> 
> ```
> 
> LD_RUNPATH_SEARCH_PATHS = (
> 					"$(inherited)",
> 					"@executable_path/Frameworks",
> 					"@loader_path/Frameworks",
> 				);
> ```
> 
> It took me 2 days to figure this out. I hope it helps

works like a charm mate, thanks

**Comment by DurgaAchyuth** [comment]
```
duplicate symbol '_OBJC_CLASS_$_PodsDummy_Pods_APBToygerFacade' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/App-eudtyouycnvgsrfqawvthsrqkzvr/Build/Products/Debug-iphoneos/APBToygerFacade.framework/APBToygerFacade[arm64][32](Pods-APBToygerFacade-dummy.o)
    /Users/mac/Library/Developer/Xcode/DerivedData/App-eudtyouycnvgsrfqawvthsrqkzvr/Build/Products/Debug-iphoneos/APBToygerFacade.framework/APBToygerFacade[arm64][31](Pods-APBToygerFacade-dummy.o)
duplicate symbol '_OBJC_METACLASS_$_PodsDummy_Pods_APBToygerFacade' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/App-eudtyouycnvgsrfqawvthsrqkzvr/Build/Products/Debug-iphoneos/APBToygerFacade.framework/APBToygerFacade[arm64][32](Pods-APBToygerFacade-dummy.o)
    /Users/mac/Library/Developer/Xcode/DerivedData/App-eudtyouycnvgsrfqawvthsrqkzvr/Build/Products/Debug-iphoneos/APBToygerFacade.framework/APBToygerFacade[arm64][31](Pods-APBToygerFacade-dummy.o)
ld: 2 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```


Anyone is facing this issue again with **Xcode 26** and try to build the app in physical **iPhone iOS 26** version
